config/routes.rb
Wapero::Application.routes.draw do

  resources :events do
    resources :possible_dates
    member do
        post 'join'
        delete 'leave'
        post 'comment'
      end
  end
  resources :ideas
  devise_for :users
  resources :users, :only => [:show, :index]
  root :to => "home#index"

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes 
  field :title, :type => String
  field :event_day, :type => DateTime
  field :description, :type => String
  field :location, :type => String
  field :geocoded, :type => Hash
  field :has_date, :type => Boolean, :default => false
  attr_accessible :title, :event_day, :possible_dates,:possible_dates_attributes, :description , :users, :location, :geocoded, :has_date
  belongs_to :creator , class_name: "User", inverse_of: :events_created
  has_and_belongs_to_many :users, :inverse_of => :events
  
  embeds_many :comments
  embeds_many :possible_dates
  accepts_nested_attributes_for :possible_dates
  scope :future , desc("event_day").where(:event_day.gte => Time.now)
  scope :past , desc("event_day").where(:event_day.lte => Time.now)
  
  index :event_day
  index :title
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_filter :authenticate_user! , :except => [:show, :index]
  before_filter :is_admin! , :except => [:show,:index, :join, :leave, :comment]
  
  
  def is_admin!
    if authenticate_user!
      unless current_user.is_admin?
        flash[:warning] = "You're not the right user!"
        redirect_to root_url
      end
    end
  end
  # GET /events
  # GET /events.json
  def index
    @events = Event.desc("event_day").all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
logger.info @event.to_json
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @event.event_day = Time.new
    @event.possible_dates << PossibleDate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.create(params[:event])
    @event.creator = current_user
    
    # TODO: DRY this
    require 'net/http'
    url = URI.parse('http://maps.googleapis.com/maps/api/geocode/json?address='+URI.encode(@event.location)+'&sensor=false')
    r = Net::HTTP.get_response(url)
    j = JSON::parse(r.body)
    @event.geocoded = j

    
    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.json  { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    # TODO: DRY this
    require 'net/http'
    url = URI.parse('http://maps.googleapis.com/maps/api/geocode/json?address='+URI.encode(@event.location)+'&sensor=false')
    r = Net::HTTP.get_response(url)
    j = JSON::parse(r.body)
    @event.geocoded = j

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.json  { head :ok }
    end
  end
  
  # POST /events/1/participate
  # POST /events/1/participate.json
  def join
    @event = Event.find(params[:id])
    if (!@event.users.include? current_user)
      @event.users << current_user
    end
    
    respond_to do |format|
      if @event.update
        format.html { redirect_to(@event) }
        format.json  { head :ok }
      else
        format.html { render :action => "show" }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /events/1/participate
  # DELETE /events/1/participate.json
  def leave
    @event = Event.find(params[:id])
    @event.users.delete current_user
    current_user.events.delete @event
    current_user.update
    
    respond_to do |format|
      if @event.update
        format.html { redirect_to(@event) }
        format.json  { head :ok }
      else
        format.html { render :action => "show" }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # POST /events/1/vote/date_id
  # POST /events/1/vote/date_id.json
  def vote_for
    @event = Event.find(params[:id])
    
    
    respond_to do |format|
      if @event.update
        format.html { redirect_to(@event) }
        format.json  { head :ok }
      else
        format.html { render :action => "show" }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # POST /events/1/comment
  def comment
    @event = Event.find(params[:id])
    @comment = Comment.new
    @comment.comment_body = params[:comment]
    @comment.author = current_user
    @event.comments << @comment
    respond_to do |format|
      if @event.update
        format.html { redirect_to(@event) }
        format.json  { head :ok }
      else
        format.html { render :action => "show" }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  

end

app/helpers/events_helper.rb
module EventsHelper
  def link_to_add_fields(name, f, association)  
    new_object = f.object.class.reflect_on_association(association).klass.new  
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|  
      puts builder
         render(association.to_s.singularize + "_fields", :f => builder)  
       
    end  
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")  
  end
end

app/views/events/_comment_form.html.erb
<div class="form_inline">
  	<%= form_tag comment_event_path do %>
	<%= label_tag(:comment, "Post a comment:") %><br/>
	  <%= text_area_tag(:comment) %>
	  <div class="actions">
	    <%= submit_tag "Comment" %>
	  </div>
	<% end %>
</div>

app/views/events/_form.html.erb
<div class="form">
  <%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :has_date %>
    <%= f.check_box :has_date %>
  </div>
  <div class="field">
    <%= f.label :event_day %><br>
    <%= f.datetime_select(:event_day, :prompt => {:day => 'Day', :month => 'Month', :year => 'Year'}, :order => [:day, :month, :year], :start_year =>     Date.today.year, :end_year => Date.today.year + 2, :minute_step => 	15, :datetime_separator => '', :time_separator => '') %>
  </div>
  <div class="field">
    <%= f.label :possible_dates %>
    <%= f.fields_for :possible_dates do |p| %>
      <%= render 'possible_date_fields', :f => p %>  
    <% end %>  
    <p><%= link_to_add_fields "Add Date", f, :possible_dates %></p>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
    <small><a href="http://daringfireball.net/projects/markdown/">Markdown accepted</a></small>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/events/_possible_date_fields.html.erb
<div class="field">
    <%= f.datetime_select(:date, :prompt => {:day => 'Day', :month => 'Month', :year => 'Year'}, :order => [:day, :month, :year], :start_year =>     Date.today.year, :end_year => Date.today.year + 2, :minute_step => 	15, :datetime_separator => '', :time_separator => '') %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>All the Waperos</h1>

<ul class="list">
<% @events.each do |event| %>
  <li><span class="event"><%= link_to event.title, event %> </span><span class="role"> - <%= event.event_day.strftime '%d/%m/%y %I:%M' %> - Participants : <%= event.users.size%></span><% if is_admin? %>  <br/>(<%= link_to 'Edit', edit_event_path(event) %>, <%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %>)<%end%></li>
<% end %>
</ul>

<% if is_admin? %><%= link_to 'New Event', new_event_path %><%end%>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
	<h1><%= @event.title %> <%if @event.has_date? %><span class=date>- <%=@event.event_day.strftime '%d/%m/%y %H:%M'%>  </span><%end%></h1> 
	  <%if @event.event_day > DateTime.now %>
      <%if @event.has_date? %> 
        <%if !@event.users.include? current_user%>
          <%= link_to 'Join', join_event_path(@event), :method => :post, :class => "button_link join"%>
        <%else%>
          <%= link_to 'Leave', leave_event_path(@event) , :method => :delete, :class => "button_link join"%>
        <%end%>
      <%end%>
    <%end%>
  <p class=description>
    <%= markdown(@event.description) %>
  </p>
  <p>
  	<strong>Lieu:</strong>
    <% if not @event.geocoded.nil? and @event.geocoded['status'] == 'OK' %>
    <div id="map" style="width: 100%; height: 300px;">&nbsp;</div>
    <% end %>
  </p>
  <p><%= @event.location %></p>
  <%if !@event.has_date? %>
  <strong>Dates Possibles:</strong>
  <ul>
  <% @event.possible_dates.sort {|x,y| x.date <=> y.date }.each do |possible_date|%>
    <li>
      <%=possible_date.date.strftime '%d/%m/%y %H:%M'%>
      <%if user_signed_in? && !possible_date.voters.include?(current_user.id)%>
        <%= link_to image_tag('heart.png'), [@event, possible_date], :method => :put, :class => "vote"%>
      <%end%>
      <%if user_signed_in? && possible_date.voters.include?(current_user.id)%>
        <%= link_to image_tag('heart_red.png'), [@event, possible_date], :method => :put, :class => "vote"%>
      <%end%>
      <%if !user_signed_in? %>
        <%= image_tag('heart.png' , :class => "vote")%>
      <%end%>
      <span class=voters><%=possible_date.voters.size%></span>
    </li>
  <%end%>
  </ul>
  <%end%>
  <p>
    <strong>Participants:</strong>
    <ul>
      <% @event.users.each do |user|%>
        <li><%= link_to user.name, user %></li>
      <%end%>
    </ul>
    
  </p>
  <p>
	<strong>Comments:</strong>
	<ul class=comments>
	<% @event.comments.lifo.each do |comment| %>
		<li><%= link_to gravatar_image_tag(comment.author.email), comment.author , :class => 'gravatar_link'%><span class=comment_info>  <%=comment.created_at.strftime '%d.%m.%y %H:%M'%></span><%= markdown(comment.comment_body)%> </li>
	<%end%>
	</ul>
  	<%if user_signed_in?%>
		<%= render "comment_form" %>
	<%end%>
  </p>



<% if not @event.geocoded.nil? and @event.geocoded['status'] == 'OK' %>
  <% content_for :javascript_includes do %>
  <script type="text/javascript"
      src="http://maps.google.com/maps/api/js?sensor=true">
  </script>
  <script type="text/javascript">
    function initialize() {
      var latlng = new google.maps.LatLng(<%= @event.geocoded['results'][0]['geometry']['location']['lat'] %>, <%= @event.geocoded['results'][0]['geometry']['location']['lng'] %>);
      var myOptions = {
        zoom: 14,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map"),
        myOptions);
      var marker = new google.maps.Marker({
        position: latlng,
        title:"<%= @event.location %>"
      });
      // To add the marker to the map, call setMap();
      marker.setMap(map); 
    }

    $(window).bind('load', initialize);
  </script>
  <% end %>
<% end %>